-- Tabela de Estados (para integração com ViaCEP)
CREATE TABLE CAD_ESTADO (
    EST_ID INTEGER PRIMARY KEY,
    EST_SIGLA CHAR(2) NOT NULL UNIQUE,
    EST_NOME VARCHAR(50) NOT NULL,
    EST_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    EST_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EST_DT_ATUALIZACAO TIMESTAMP
);

-- Tabela de Cidades (para integração com ViaCEP)
CREATE TABLE CAD_CIDADE (
    CID_ID INTEGER PRIMARY KEY,
    CID_NOME VARCHAR(100) NOT NULL,
    CID_CODIGO_IBGE VARCHAR(10),
    EST_ID INTEGER NOT NULL,
    CID_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CID_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CID_DT_ATUALIZACAO TIMESTAMP,
    FOREIGN KEY (EST_ID) REFERENCES CAD_ESTADO(EST_ID)
);

-- Tabela de Endereços (integração com ViaCEP)
CREATE TABLE CAD_ENDERECO (
    END_ID INTEGER PRIMARY KEY,
    END_CEP VARCHAR(10) NOT NULL,
    END_LOGRADOURO VARCHAR(200) NOT NULL,
    END_NUMERO VARCHAR(20),
    END_COMPLEMENTO VARCHAR(100),
    END_BAIRRO VARCHAR(100) NOT NULL,
    CID_ID INTEGER NOT NULL,
    END_REFERENCIA VARCHAR(200),
    END_TIPO CHAR(1) NOT NULL, -- 'C' = Comercial, 'R' = Residencial, 'E' = Entrega
    END_PRINCIPAL BOOLEAN NOT NULL DEFAULT FALSE,
    END_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    END_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_DT_ATUALIZACAO TIMESTAMP,
    FOREIGN KEY (CID_ID) REFERENCES CAD_CIDADE(CID_ID)
);

-- Tabela de Clientes (corrigida e melhorada)
CREATE TABLE CAD_CLIENTE (
    CLI_ID INTEGER PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF_CNPJ VARCHAR(20) NOT NULL UNIQUE,
    CLI_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CLI_DT_ULTIMA_COMPRA DATE,
    CLI_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLI_DT_ATUALIZACAO TIMESTAMP,
    CLI_TIPO_PESSOA CHAR(1) NOT NULL CHECK (CLI_TIPO_PESSOA IN ('F', 'J')), -- F = Física, J = Jurídica
    CLI_OBSERVACOES TEXT,
    CONSTRAINT chk_cpf_cnpj CHECK (
        (CLI_TIPO_PESSOA = 'F' AND LENGTH(REPLACE(REPLACE(CLI_CPF_CNPJ, '.', ''), '-', '')) = 11) OR
        (CLI_TIPO_PESSOA = 'J' AND LENGTH(REPLACE(REPLACE(REPLACE(CLI_CPF_CNPJ, '.', ''), '/', ''), '-', '')) = 14)
    )
);

-- Tabela de Vendedores (corrigida e melhorada)
CREATE TABLE CAD_VENDEDOR (
    VEN_ID INTEGER PRIMARY KEY,
    VEN_NOME VARCHAR(100) NOT NULL,
    VEN_CPF_CNPJ VARCHAR(20) NOT NULL UNIQUE,
    VEN_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    VEN_DT_ULTIMA_VENDA DATE,
    VEN_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VEN_DT_ATUALIZACAO TIMESTAMP,
    VEN_TIPO_PESSOA CHAR(1) NOT NULL CHECK (VEN_TIPO_PESSOA IN ('F', 'J')), -- F = Física, J = Jurídica
    VEN_COMISSAO DECIMAL(5,2) DEFAULT 0.00, -- Percentual de comissão
    VEN_OBSERVACOES TEXT,
    CONSTRAINT chk_ven_cpf_cnpj CHECK (
        (VEN_TIPO_PESSOA = 'F' AND LENGTH(REPLACE(REPLACE(VEN_CPF_CNPJ, '.', ''), '-', '')) = 11) OR
        (VEN_TIPO_PESSOA = 'J' AND LENGTH(REPLACE(REPLACE(REPLACE(VEN_CPF_CNPJ, '.', ''), '/', ''), '-', '')) = 14)
    )
);

-- Tabela de Produtos (melhorada)
CREATE TABLE CAD_PRODUTO (
    PRO_ID INTEGER PRIMARY KEY,
    PRO_DESCRICAO VARCHAR(100) NOT NULL,
    PRO_CODIGO_BARRAS VARCHAR(30) UNIQUE,
    PRO_PRECO_VENDA DECIMAL(10,2) NOT NULL CHECK (PRO_PRECO_VENDA >= 0),
    PRO_QUANTIDADE_ESTOQUE INTEGER NOT NULL DEFAULT 0 CHECK (PRO_QUANTIDADE_ESTOQUE >= 0),
    PRO_ESTOQUE_MINIMO INTEGER DEFAULT 0 CHECK (PRO_ESTOQUE_MINIMO >= 0),
    PRO_UNIDADE_MEDIDA VARCHAR(10) NOT NULL DEFAULT 'UN',
    PRO_PESO DECIMAL(8,3), -- Para cálculo de frete
    PRO_DIMENSOES VARCHAR(50), -- LxAxP em cm (ex: "30x20x10")
    PRO_CATEGORIA VARCHAR(50),
    PRO_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    PRO_DT_ULTIMA_VENDA DATE,
    PRO_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRO_DT_ATUALIZACAO TIMESTAMP,
    PRO_OBSERVACOES TEXT
);

-- Tabela de Formas de Pagamento (melhorada)
CREATE TABLE CAD_FORMA_PAGAMENTO (
    FPG_ID INTEGER PRIMARY KEY,
    FPG_DESCRICAO VARCHAR(50) NOT NULL UNIQUE,
    FPG_TAXA DECIMAL(5,2) DEFAULT 0.00 CHECK (FPG_TAXA >= 0),
    FPG_PRAZO_DIAS INTEGER DEFAULT 0, -- Prazo em dias para pagamento
    FPG_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    FPG_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FPG_DT_ATUALIZACAO TIMESTAMP
);

-- Tabela de relacionamento Cliente-Endereço
CREATE TABLE CAD_CLIENTE_ENDERECO (
    CLI_ID INTEGER NOT NULL,
    END_ID INTEGER NOT NULL,
    CEE_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CLI_ID, END_ID),
    FOREIGN KEY (CLI_ID) REFERENCES CAD_CLIENTE(CLI_ID) ON DELETE CASCADE,
    FOREIGN KEY (END_ID) REFERENCES CAD_ENDERECO(END_ID) ON DELETE CASCADE
);

-- Tabela de relacionamento Vendedor-Endereço
CREATE TABLE CAD_VENDEDOR_ENDERECO (
    VEN_ID INTEGER NOT NULL,
    END_ID INTEGER NOT NULL,
    VEE_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (VEN_ID, END_ID),
    FOREIGN KEY (VEN_ID) REFERENCES CAD_VENDEDOR(VEN_ID) ON DELETE CASCADE,
    FOREIGN KEY (END_ID) REFERENCES CAD_ENDERECO(END_ID) ON DELETE CASCADE
);

-- Tabela de Contatos (corrigida - não pode referenciar cliente E vendedor ao mesmo tempo)
CREATE TABLE CAD_CONTATO (
    CON_ID INTEGER PRIMARY KEY,
    CON_VALOR VARCHAR(100) NOT NULL,
    CLI_ID INTEGER,
    VEN_ID INTEGER,
    CON_ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CON_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CON_DT_ATUALIZACAO TIMESTAMP,
    CON_TIPO CHAR(1) NOT NULL CHECK (CON_TIPO IN ('E', 'T', 'W')), -- E = Email, T = Telefone, W = WhatsApp
    FOREIGN KEY (CLI_ID) REFERENCES CAD_CLIENTE(CLI_ID) ON DELETE CASCADE,
    FOREIGN KEY (VEN_ID) REFERENCES CAD_VENDEDOR(VEN_ID) ON DELETE CASCADE,
    CONSTRAINT chk_contato_owner CHECK ((CLI_ID IS NOT NULL AND VEN_ID IS NULL) OR (CLI_ID IS NULL AND VEN_ID IS NOT NULL))
);