CREATE TABLE CAD_CLIENTE (
    CLI_ID INTEGER PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF_CNPJ VARCHAR(20) NOT NULL,
    CLI_ATIVO BOOLEAN NOT NULL,
    CLI_DT_ULTIMA_COMPRA DATE,
    CLI_DT_CRIACAO TIMESTAMP NOT NULL,
    CLI_DT_ATUALIZACAO TIMESTAMP,
    CLI_TIPO_PESSOA CHAR(1) NOT NULL
);

CREATE TABLE CAD_VENDEDOR (
    VEN_ID INTEGER PRIMARY KEY,
    VEN_NOME VARCHAR(100) NOT NULL,
    VEN_CPF_CNPJ VARCHAR(20) NOT NULL,
    VEN_ATIVO BOOLEAN NOT NULL,
    VEN_DT_ULTIMA_VENDA DATE,
    VEN_DT_CRIACAO TIMESTAMP NOT NULL,
    VEN_DT_ATUALIZACAO TIMESTAMP,
    VEN_TIPO_PESSOA CHAR(1) NOT NULL
);

CREATE TABLE CAD_PRODUTO (
    PRO_ID INTEGER PRIMARY KEY,
    PRO_DESCRICAO VARCHAR(100) NOT NULL,
    PRO_CODIGO_BARRAS VARCHAR(30),
    PRO_PRECO_VENDA DECIMAL(10,2) NOT NULL,
    PRO_QUANTIDADE_ESTOQUE INTEGER NOT NULL,
    PRO_ESTOQUE_MINIMO INTEGER,
    PRO_UNIDADE_MEDIDA VARCHAR(10),
    PRO_ATIVO BOOLEAN NOT NULL,
    PRO_DT_ULTIMA_VENDA DATE,
    PRO_DT_CRIACAO TIMESTAMP NOT NULL,
    PRO_DT_ATUALIZACAO TIMESTAMP
);

CREATE TABLE CAD_FORMA_PAGAMENTO (
    FPG_ID INTEGER PRIMARY KEY,
    FPG_DESCRICAO VARCHAR(50) NOT NULL,
    FPG_TAXA DECIMAL(5,2),
    FPG_ATIVO BOOLEAN NOT NULL,
    FPG_DT_CRIACAO TIMESTAMP NOT NULL,
    FPG_DT_ATUALIZACAO TIMESTAMP
);