-- Tabela principal de Vendas (melhorada com suporte a entregas)
CREATE TABLE VENDA (
    VND_ID INTEGER PRIMARY KEY,
    CLI_ID INTEGER NOT NULL,
    VEN_ID INTEGER NOT NULL,
    FPG_ID INTEGER NOT NULL,
    END_ENTREGA_ID INTEGER, -- Endereço de entrega (opcional para retirada)
    VND_DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VND_VALOR_PRODUTOS DECIMAL(10,2) NOT NULL CHECK (VND_VALOR_PRODUTOS >= 0),
    VND_VALOR_FRETE DECIMAL(10,2) DEFAULT 0.00 CHECK (VND_VALOR_FRETE >= 0),
    VND_VALOR_DESCONTO DECIMAL(10,2) DEFAULT 0.00 CHECK (VND_VALOR_DESCONTO >= 0),
    VND_VALOR_TOTAL DECIMAL(10,2) NOT NULL CHECK (VND_VALOR_TOTAL >= 0),
    VND_STATUS VARCHAR(20) DEFAULT 'Pendente' CHECK (VND_STATUS IN ('Pendente', 'Confirmado', 'Enviado', 'Entregue', 'Cancelado')),
    VND_TIPO_ENTREGA CHAR(3) NOT NULL DEFAULT 'RET' CHECK (VND_TIPO_ENTREGA IN ('CIF', 'FOB', 'RET')), -- CIF = Custo, seguro e frete por conta do vendedor, FOB = Frete por conta do comprador, RET = Retirada
    VND_DT_PREVISTA_ENTREGA DATE,
    VND_DT_ENTREGA DATE,
    VND_OBSERVACOES TEXT,
    VND_NUMERO_PEDIDO VARCHAR(50), -- Número do pedido para controle
    VND_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VND_DT_ATUALIZACAO TIMESTAMP,
    FOREIGN KEY (CLI_ID) REFERENCES CAD_CLIENTE(CLI_ID),
    FOREIGN KEY (VEN_ID) REFERENCES CAD_VENDEDOR(VEN_ID),
    FOREIGN KEY (FPG_ID) REFERENCES CAD_FORMA_PAGAMENTO(FPG_ID),
    FOREIGN KEY (END_ENTREGA_ID) REFERENCES CAD_ENDERECO(END_ID),
    -- Constraint para garantir que entregas CIF/FOB tenham endereço
    CONSTRAINT chk_endereco_entrega CHECK (
        (VND_TIPO_ENTREGA = 'RET' AND END_ENTREGA_ID IS NULL) OR
        (VND_TIPO_ENTREGA IN ('CIF', 'FOB') AND END_ENTREGA_ID IS NOT NULL)
    )
);

-- Tabela de itens da venda (melhorada)
CREATE TABLE VENDA_ITEM (
    VNI_ID INTEGER PRIMARY KEY,
    VND_ID INTEGER NOT NULL,
    PRO_ID INTEGER NOT NULL,
    VNI_QUANTIDADE INTEGER NOT NULL CHECK (VNI_QUANTIDADE > 0),
    VNI_PRECO_UNITARIO DECIMAL(10,2) NOT NULL CHECK (VNI_PRECO_UNITARIO >= 0),
    VNI_DESCONTO DECIMAL(5,2) DEFAULT 0.00 CHECK (VNI_DESCONTO >= 0 AND VNI_DESCONTO <= 100),
    VNI_VALOR_TOTAL DECIMAL(10,2) NOT NULL CHECK (VNI_VALOR_TOTAL >= 0),
    VNI_OBSERVACOES VARCHAR(500),
    VNI_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VND_ID) REFERENCES VENDA(VND_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRO_ID) REFERENCES CAD_PRODUTO(PRO_ID)
);

-- Tabela para histórico de status da venda (rastreabilidade)
CREATE TABLE VENDA_STATUS_HISTORICO (
    VSH_ID INTEGER PRIMARY KEY,
    VND_ID INTEGER NOT NULL,
    VSH_STATUS_ANTERIOR VARCHAR(20),
    VSH_STATUS_NOVO VARCHAR(20) NOT NULL,
    VSH_DT_MUDANCA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VSH_OBSERVACAO TEXT,
    VSH_USUARIO VARCHAR(100), -- Quem fez a alteração
    FOREIGN KEY (VND_ID) REFERENCES VENDA(VND_ID) ON DELETE CASCADE
);

-- Tabela para informações de frete (quando aplicável)
CREATE TABLE VENDA_FRETE (
    VFR_ID INTEGER PRIMARY KEY,
    VND_ID INTEGER NOT NULL UNIQUE,
    VFR_TRANSPORTADORA VARCHAR(100),
    VFR_CODIGO_RASTREIO VARCHAR(50),
    VFR_PRAZO_ENTREGA INTEGER, -- Dias úteis
    VFR_PESO_TOTAL DECIMAL(8,3),
    VFR_VALOR_DECLARADO DECIMAL(10,2),
    VFR_DT_POSTAGEM TIMESTAMP,
    VFR_DT_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VFR_DT_ATUALIZACAO TIMESTAMP,
    FOREIGN KEY (VND_ID) REFERENCES VENDA(VND_ID) ON DELETE CASCADE
);