CREATE TABLE VENDA (
    VND_ID INTEGER PRIMARY KEY,
    CLI_ID INTEGER NOT NULL,
    VEN_ID INTEGER NOT NULL,
    FPG_ID INTEGER NOT NULL,
    VND_DATA TIMESTAMP NOT NULL,
    VND_VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    VND_STATUS VARCHAR(20) DEFAULT 'Pendente',
    FOREIGN KEY (CLI_ID) REFERENCES CAD_CLIENTE(CLI_ID),
    FOREIGN KEY (VEN_ID) REFERENCES CAD_VENDEDOR(VEN_ID),
    FOREIGN KEY (FPG_ID) REFERENCES CAD_FORMA_PAGAMENTO(FPG_ID)
);

CREATE TABLE VENDA_ITEM (
    VNI_ID INTEGER PRIMARY KEY,
    VND_ID INTEGER NOT NULL,
    PRO_ID INTEGER NOT NULL,
    VNI_QUANTIDADE INTEGER NOT NULL,
    VNI_PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    VNI_DESCONTO DECIMAL(5,2) DEFAULT 0,
    FOREIGN KEY (VND_ID) REFERENCES VENDA(VND_ID),
    FOREIGN KEY (PRO_ID) REFERENCES CAD_PRODUTO(PRO_ID)
);