CREATE TABLE CAD_USUARIO (
    USR_ID INTEGER PRIMARY KEY,
    USR_NOME VARCHAR(100) NOT NULL,
    USR_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USR_SENHA_HASH VARCHAR(255) NOT NULL,
    USR_ATIVO BOOLEAN NOT NULL,
    USR_DT_CRIACAO TIMESTAMP NOT NULL,
    USR_DT_ATUALIZACAO TIMESTAMP
);

